###consul服务端口号
server:
  port: 8003

spring:
  application:
    name: consul-provider-service
  ####consul注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        #hostname: 127.0.0.1
        service-name: ${spring.application.name}
